/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fever.plans_management_system.kafka_messaging_contracts.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BasePlan extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2261879113668746648L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BasePlan\",\"namespace\":\"com.fever.plans_management_system.kafka_messaging_contracts.dto\",\"fields\":[{\"name\":\"base_plan_id\",\"type\":\"long\"},{\"name\":\"sell_mode\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"plans\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Plan\",\"fields\":[{\"name\":\"plan_id\",\"type\":\"long\"},{\"name\":\"plan_start_date\",\"type\":\"string\"},{\"name\":\"plan_end_date\",\"type\":\"string\"},{\"name\":\"sell_from\",\"type\":\"string\"},{\"name\":\"sell_to\",\"type\":\"string\"},{\"name\":\"sold_out\",\"type\":\"boolean\"},{\"name\":\"zones\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Zone\",\"fields\":[{\"name\":\"zone_id\",\"type\":\"long\"},{\"name\":\"capacity\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"numbered\",\"type\":\"boolean\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BasePlan> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BasePlan> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BasePlan> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BasePlan> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BasePlan> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BasePlan to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BasePlan from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BasePlan instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BasePlan fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long base_plan_id;
  private java.lang.CharSequence sell_mode;
  private java.lang.CharSequence title;
  private java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> plans;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BasePlan() {}

  /**
   * All-args constructor.
   * @param base_plan_id The new value for base_plan_id
   * @param sell_mode The new value for sell_mode
   * @param title The new value for title
   * @param plans The new value for plans
   */
  public BasePlan(java.lang.Long base_plan_id, java.lang.CharSequence sell_mode, java.lang.CharSequence title, java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> plans) {
    this.base_plan_id = base_plan_id;
    this.sell_mode = sell_mode;
    this.title = title;
    this.plans = plans;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return base_plan_id;
    case 1: return sell_mode;
    case 2: return title;
    case 3: return plans;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: base_plan_id = (java.lang.Long)value$; break;
    case 1: sell_mode = (java.lang.CharSequence)value$; break;
    case 2: title = (java.lang.CharSequence)value$; break;
    case 3: plans = (java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'base_plan_id' field.
   * @return The value of the 'base_plan_id' field.
   */
  public long getBasePlanId() {
    return base_plan_id;
  }


  /**
   * Sets the value of the 'base_plan_id' field.
   * @param value the value to set.
   */
  public void setBasePlanId(long value) {
    this.base_plan_id = value;
  }

  /**
   * Gets the value of the 'sell_mode' field.
   * @return The value of the 'sell_mode' field.
   */
  public java.lang.CharSequence getSellMode() {
    return sell_mode;
  }


  /**
   * Sets the value of the 'sell_mode' field.
   * @param value the value to set.
   */
  public void setSellMode(java.lang.CharSequence value) {
    this.sell_mode = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'plans' field.
   * @return The value of the 'plans' field.
   */
  public java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> getPlans() {
    return plans;
  }


  /**
   * Sets the value of the 'plans' field.
   * @param value the value to set.
   */
  public void setPlans(java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> value) {
    this.plans = value;
  }

  /**
   * Creates a new BasePlan RecordBuilder.
   * @return A new BasePlan RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder newBuilder() {
    return new com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder();
  }

  /**
   * Creates a new BasePlan RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BasePlan RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder newBuilder(com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder other) {
    if (other == null) {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder();
    } else {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder(other);
    }
  }

  /**
   * Creates a new BasePlan RecordBuilder by copying an existing BasePlan instance.
   * @param other The existing instance to copy.
   * @return A new BasePlan RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder newBuilder(com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan other) {
    if (other == null) {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder();
    } else {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder(other);
    }
  }

  /**
   * RecordBuilder for BasePlan instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BasePlan>
    implements org.apache.avro.data.RecordBuilder<BasePlan> {

    private long base_plan_id;
    private java.lang.CharSequence sell_mode;
    private java.lang.CharSequence title;
    private java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> plans;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.base_plan_id)) {
        this.base_plan_id = data().deepCopy(fields()[0].schema(), other.base_plan_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sell_mode)) {
        this.sell_mode = data().deepCopy(fields()[1].schema(), other.sell_mode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.plans)) {
        this.plans = data().deepCopy(fields()[3].schema(), other.plans);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing BasePlan instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.base_plan_id)) {
        this.base_plan_id = data().deepCopy(fields()[0].schema(), other.base_plan_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sell_mode)) {
        this.sell_mode = data().deepCopy(fields()[1].schema(), other.sell_mode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.plans)) {
        this.plans = data().deepCopy(fields()[3].schema(), other.plans);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'base_plan_id' field.
      * @return The value.
      */
    public long getBasePlanId() {
      return base_plan_id;
    }


    /**
      * Sets the value of the 'base_plan_id' field.
      * @param value The value of 'base_plan_id'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder setBasePlanId(long value) {
      validate(fields()[0], value);
      this.base_plan_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'base_plan_id' field has been set.
      * @return True if the 'base_plan_id' field has been set, false otherwise.
      */
    public boolean hasBasePlanId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'base_plan_id' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder clearBasePlanId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sell_mode' field.
      * @return The value.
      */
    public java.lang.CharSequence getSellMode() {
      return sell_mode;
    }


    /**
      * Sets the value of the 'sell_mode' field.
      * @param value The value of 'sell_mode'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder setSellMode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sell_mode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sell_mode' field has been set.
      * @return True if the 'sell_mode' field has been set, false otherwise.
      */
    public boolean hasSellMode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sell_mode' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder clearSellMode() {
      sell_mode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.title = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder clearTitle() {
      title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'plans' field.
      * @return The value.
      */
    public java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> getPlans() {
      return plans;
    }


    /**
      * Sets the value of the 'plans' field.
      * @param value The value of 'plans'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder setPlans(java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> value) {
      validate(fields()[3], value);
      this.plans = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'plans' field has been set.
      * @return True if the 'plans' field has been set, false otherwise.
      */
    public boolean hasPlans() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'plans' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.BasePlan.Builder clearPlans() {
      plans = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BasePlan build() {
      try {
        BasePlan record = new BasePlan();
        record.base_plan_id = fieldSetFlags()[0] ? this.base_plan_id : (java.lang.Long) defaultValue(fields()[0]);
        record.sell_mode = fieldSetFlags()[1] ? this.sell_mode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.title = fieldSetFlags()[2] ? this.title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.plans = fieldSetFlags()[3] ? this.plans : (java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BasePlan>
    WRITER$ = (org.apache.avro.io.DatumWriter<BasePlan>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BasePlan>
    READER$ = (org.apache.avro.io.DatumReader<BasePlan>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.base_plan_id);

    out.writeString(this.sell_mode);

    out.writeString(this.title);

    long size0 = this.plans.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan e0: this.plans) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.base_plan_id = in.readLong();

      this.sell_mode = in.readString(this.sell_mode instanceof Utf8 ? (Utf8)this.sell_mode : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      long size0 = in.readArrayStart();
      java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> a0 = this.plans;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>((int)size0, SCHEMA$.getField("plans").schema());
        this.plans = a0;
      } else a0.clear();
      SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.base_plan_id = in.readLong();
          break;

        case 1:
          this.sell_mode = in.readString(this.sell_mode instanceof Utf8 ? (Utf8)this.sell_mode : null);
          break;

        case 2:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> a0 = this.plans;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>((int)size0, SCHEMA$.getField("plans").schema());
            this.plans = a0;
          } else a0.clear();
          SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.fever.plans_management_system.kafka_messaging_contracts.dto.Plan();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










