/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fever.plans_management_system.kafka_messaging_contracts.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlanAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3843883438782804115L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlanAvro\",\"namespace\":\"com.fever.plans_management_system.kafka_messaging_contracts.dto\",\"fields\":[{\"name\":\"plan_id\",\"type\":\"long\"},{\"name\":\"plan_start_date\",\"type\":\"string\"},{\"name\":\"plan_end_date\",\"type\":\"string\"},{\"name\":\"sell_from\",\"type\":\"string\"},{\"name\":\"sell_to\",\"type\":\"string\"},{\"name\":\"sold_out\",\"type\":\"boolean\"},{\"name\":\"zones\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ZoneAvro\",\"fields\":[{\"name\":\"zone_id\",\"type\":\"long\"},{\"name\":\"capacity\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"numbered\",\"type\":\"boolean\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PlanAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlanAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlanAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlanAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlanAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlanAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlanAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlanAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlanAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long plan_id;
  private java.lang.CharSequence plan_start_date;
  private java.lang.CharSequence plan_end_date;
  private java.lang.CharSequence sell_from;
  private java.lang.CharSequence sell_to;
  private boolean sold_out;
  private java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> zones;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlanAvro() {}

  /**
   * All-args constructor.
   * @param plan_id The new value for plan_id
   * @param plan_start_date The new value for plan_start_date
   * @param plan_end_date The new value for plan_end_date
   * @param sell_from The new value for sell_from
   * @param sell_to The new value for sell_to
   * @param sold_out The new value for sold_out
   * @param zones The new value for zones
   */
  public PlanAvro(java.lang.Long plan_id, java.lang.CharSequence plan_start_date, java.lang.CharSequence plan_end_date, java.lang.CharSequence sell_from, java.lang.CharSequence sell_to, java.lang.Boolean sold_out, java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> zones) {
    this.plan_id = plan_id;
    this.plan_start_date = plan_start_date;
    this.plan_end_date = plan_end_date;
    this.sell_from = sell_from;
    this.sell_to = sell_to;
    this.sold_out = sold_out;
    this.zones = zones;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return plan_id;
    case 1: return plan_start_date;
    case 2: return plan_end_date;
    case 3: return sell_from;
    case 4: return sell_to;
    case 5: return sold_out;
    case 6: return zones;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: plan_id = (java.lang.Long)value$; break;
    case 1: plan_start_date = (java.lang.CharSequence)value$; break;
    case 2: plan_end_date = (java.lang.CharSequence)value$; break;
    case 3: sell_from = (java.lang.CharSequence)value$; break;
    case 4: sell_to = (java.lang.CharSequence)value$; break;
    case 5: sold_out = (java.lang.Boolean)value$; break;
    case 6: zones = (java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'plan_id' field.
   * @return The value of the 'plan_id' field.
   */
  public long getPlanId() {
    return plan_id;
  }


  /**
   * Sets the value of the 'plan_id' field.
   * @param value the value to set.
   */
  public void setPlanId(long value) {
    this.plan_id = value;
  }

  /**
   * Gets the value of the 'plan_start_date' field.
   * @return The value of the 'plan_start_date' field.
   */
  public java.lang.CharSequence getPlanStartDate() {
    return plan_start_date;
  }


  /**
   * Sets the value of the 'plan_start_date' field.
   * @param value the value to set.
   */
  public void setPlanStartDate(java.lang.CharSequence value) {
    this.plan_start_date = value;
  }

  /**
   * Gets the value of the 'plan_end_date' field.
   * @return The value of the 'plan_end_date' field.
   */
  public java.lang.CharSequence getPlanEndDate() {
    return plan_end_date;
  }


  /**
   * Sets the value of the 'plan_end_date' field.
   * @param value the value to set.
   */
  public void setPlanEndDate(java.lang.CharSequence value) {
    this.plan_end_date = value;
  }

  /**
   * Gets the value of the 'sell_from' field.
   * @return The value of the 'sell_from' field.
   */
  public java.lang.CharSequence getSellFrom() {
    return sell_from;
  }


  /**
   * Sets the value of the 'sell_from' field.
   * @param value the value to set.
   */
  public void setSellFrom(java.lang.CharSequence value) {
    this.sell_from = value;
  }

  /**
   * Gets the value of the 'sell_to' field.
   * @return The value of the 'sell_to' field.
   */
  public java.lang.CharSequence getSellTo() {
    return sell_to;
  }


  /**
   * Sets the value of the 'sell_to' field.
   * @param value the value to set.
   */
  public void setSellTo(java.lang.CharSequence value) {
    this.sell_to = value;
  }

  /**
   * Gets the value of the 'sold_out' field.
   * @return The value of the 'sold_out' field.
   */
  public boolean getSoldOut() {
    return sold_out;
  }


  /**
   * Sets the value of the 'sold_out' field.
   * @param value the value to set.
   */
  public void setSoldOut(boolean value) {
    this.sold_out = value;
  }

  /**
   * Gets the value of the 'zones' field.
   * @return The value of the 'zones' field.
   */
  public java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> getZones() {
    return zones;
  }


  /**
   * Sets the value of the 'zones' field.
   * @param value the value to set.
   */
  public void setZones(java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> value) {
    this.zones = value;
  }

  /**
   * Creates a new PlanAvro RecordBuilder.
   * @return A new PlanAvro RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder newBuilder() {
    return new com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder();
  }

  /**
   * Creates a new PlanAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlanAvro RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder newBuilder(com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder other) {
    if (other == null) {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder();
    } else {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder(other);
    }
  }

  /**
   * Creates a new PlanAvro RecordBuilder by copying an existing PlanAvro instance.
   * @param other The existing instance to copy.
   * @return A new PlanAvro RecordBuilder
   */
  public static com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder newBuilder(com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro other) {
    if (other == null) {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder();
    } else {
      return new com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlanAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlanAvro>
    implements org.apache.avro.data.RecordBuilder<PlanAvro> {

    private long plan_id;
    private java.lang.CharSequence plan_start_date;
    private java.lang.CharSequence plan_end_date;
    private java.lang.CharSequence sell_from;
    private java.lang.CharSequence sell_to;
    private boolean sold_out;
    private java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> zones;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.plan_id)) {
        this.plan_id = data().deepCopy(fields()[0].schema(), other.plan_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.plan_start_date)) {
        this.plan_start_date = data().deepCopy(fields()[1].schema(), other.plan_start_date);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.plan_end_date)) {
        this.plan_end_date = data().deepCopy(fields()[2].schema(), other.plan_end_date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sell_from)) {
        this.sell_from = data().deepCopy(fields()[3].schema(), other.sell_from);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.sell_to)) {
        this.sell_to = data().deepCopy(fields()[4].schema(), other.sell_to);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.sold_out)) {
        this.sold_out = data().deepCopy(fields()[5].schema(), other.sold_out);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.zones)) {
        this.zones = data().deepCopy(fields()[6].schema(), other.zones);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing PlanAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.plan_id)) {
        this.plan_id = data().deepCopy(fields()[0].schema(), other.plan_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.plan_start_date)) {
        this.plan_start_date = data().deepCopy(fields()[1].schema(), other.plan_start_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.plan_end_date)) {
        this.plan_end_date = data().deepCopy(fields()[2].schema(), other.plan_end_date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sell_from)) {
        this.sell_from = data().deepCopy(fields()[3].schema(), other.sell_from);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sell_to)) {
        this.sell_to = data().deepCopy(fields()[4].schema(), other.sell_to);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sold_out)) {
        this.sold_out = data().deepCopy(fields()[5].schema(), other.sold_out);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.zones)) {
        this.zones = data().deepCopy(fields()[6].schema(), other.zones);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'plan_id' field.
      * @return The value.
      */
    public long getPlanId() {
      return plan_id;
    }


    /**
      * Sets the value of the 'plan_id' field.
      * @param value The value of 'plan_id'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setPlanId(long value) {
      validate(fields()[0], value);
      this.plan_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'plan_id' field has been set.
      * @return True if the 'plan_id' field has been set, false otherwise.
      */
    public boolean hasPlanId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'plan_id' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearPlanId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'plan_start_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getPlanStartDate() {
      return plan_start_date;
    }


    /**
      * Sets the value of the 'plan_start_date' field.
      * @param value The value of 'plan_start_date'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setPlanStartDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.plan_start_date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'plan_start_date' field has been set.
      * @return True if the 'plan_start_date' field has been set, false otherwise.
      */
    public boolean hasPlanStartDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'plan_start_date' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearPlanStartDate() {
      plan_start_date = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'plan_end_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getPlanEndDate() {
      return plan_end_date;
    }


    /**
      * Sets the value of the 'plan_end_date' field.
      * @param value The value of 'plan_end_date'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setPlanEndDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.plan_end_date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'plan_end_date' field has been set.
      * @return True if the 'plan_end_date' field has been set, false otherwise.
      */
    public boolean hasPlanEndDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'plan_end_date' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearPlanEndDate() {
      plan_end_date = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sell_from' field.
      * @return The value.
      */
    public java.lang.CharSequence getSellFrom() {
      return sell_from;
    }


    /**
      * Sets the value of the 'sell_from' field.
      * @param value The value of 'sell_from'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setSellFrom(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sell_from = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sell_from' field has been set.
      * @return True if the 'sell_from' field has been set, false otherwise.
      */
    public boolean hasSellFrom() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sell_from' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearSellFrom() {
      sell_from = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'sell_to' field.
      * @return The value.
      */
    public java.lang.CharSequence getSellTo() {
      return sell_to;
    }


    /**
      * Sets the value of the 'sell_to' field.
      * @param value The value of 'sell_to'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setSellTo(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.sell_to = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'sell_to' field has been set.
      * @return True if the 'sell_to' field has been set, false otherwise.
      */
    public boolean hasSellTo() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'sell_to' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearSellTo() {
      sell_to = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'sold_out' field.
      * @return The value.
      */
    public boolean getSoldOut() {
      return sold_out;
    }


    /**
      * Sets the value of the 'sold_out' field.
      * @param value The value of 'sold_out'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setSoldOut(boolean value) {
      validate(fields()[5], value);
      this.sold_out = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'sold_out' field has been set.
      * @return True if the 'sold_out' field has been set, false otherwise.
      */
    public boolean hasSoldOut() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'sold_out' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearSoldOut() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'zones' field.
      * @return The value.
      */
    public java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> getZones() {
      return zones;
    }


    /**
      * Sets the value of the 'zones' field.
      * @param value The value of 'zones'.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder setZones(java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> value) {
      validate(fields()[6], value);
      this.zones = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'zones' field has been set.
      * @return True if the 'zones' field has been set, false otherwise.
      */
    public boolean hasZones() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'zones' field.
      * @return This builder.
      */
    public com.fever.plans_management_system.kafka_messaging_contracts.dto.PlanAvro.Builder clearZones() {
      zones = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlanAvro build() {
      try {
        PlanAvro record = new PlanAvro();
        record.plan_id = fieldSetFlags()[0] ? this.plan_id : (java.lang.Long) defaultValue(fields()[0]);
        record.plan_start_date = fieldSetFlags()[1] ? this.plan_start_date : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.plan_end_date = fieldSetFlags()[2] ? this.plan_end_date : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sell_from = fieldSetFlags()[3] ? this.sell_from : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.sell_to = fieldSetFlags()[4] ? this.sell_to : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.sold_out = fieldSetFlags()[5] ? this.sold_out : (java.lang.Boolean) defaultValue(fields()[5]);
        record.zones = fieldSetFlags()[6] ? this.zones : (java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlanAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlanAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlanAvro>
    READER$ = (org.apache.avro.io.DatumReader<PlanAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.plan_id);

    out.writeString(this.plan_start_date);

    out.writeString(this.plan_end_date);

    out.writeString(this.sell_from);

    out.writeString(this.sell_to);

    out.writeBoolean(this.sold_out);

    long size0 = this.zones.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro e0: this.zones) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.plan_id = in.readLong();

      this.plan_start_date = in.readString(this.plan_start_date instanceof Utf8 ? (Utf8)this.plan_start_date : null);

      this.plan_end_date = in.readString(this.plan_end_date instanceof Utf8 ? (Utf8)this.plan_end_date : null);

      this.sell_from = in.readString(this.sell_from instanceof Utf8 ? (Utf8)this.sell_from : null);

      this.sell_to = in.readString(this.sell_to instanceof Utf8 ? (Utf8)this.sell_to : null);

      this.sold_out = in.readBoolean();

      long size0 = in.readArrayStart();
      java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> a0 = this.zones;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>((int)size0, SCHEMA$.getField("zones").schema());
        this.zones = a0;
      } else a0.clear();
      SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.plan_id = in.readLong();
          break;

        case 1:
          this.plan_start_date = in.readString(this.plan_start_date instanceof Utf8 ? (Utf8)this.plan_start_date : null);
          break;

        case 2:
          this.plan_end_date = in.readString(this.plan_end_date instanceof Utf8 ? (Utf8)this.plan_end_date : null);
          break;

        case 3:
          this.sell_from = in.readString(this.sell_from instanceof Utf8 ? (Utf8)this.sell_from : null);
          break;

        case 4:
          this.sell_to = in.readString(this.sell_to instanceof Utf8 ? (Utf8)this.sell_to : null);
          break;

        case 5:
          this.sold_out = in.readBoolean();
          break;

        case 6:
          long size0 = in.readArrayStart();
          java.util.List<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> a0 = this.zones;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>((int)size0, SCHEMA$.getField("zones").schema());
            this.zones = a0;
          } else a0.clear();
          SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.fever.plans_management_system.kafka_messaging_contracts.dto.ZoneAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










